// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MikesBank.Models;

namespace MikesBank.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190923160836_changeProfessionTreeStruct")]
    partial class changeProfessionTreeStruct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MikesBank.Models.Department", b =>
                {
                    b.Property<int>("DepId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepName");

                    b.Property<string>("DepOffice");

                    b.Property<int?>("LocId");

                    b.Property<string>("UpdateBy");

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("DepId");

                    b.HasIndex("LocId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("MikesBank.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepId");

                    b.Property<string>("EmpJobTitle");

                    b.Property<int?>("EmpManagerId");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UpdateBy");

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("EmpId");

                    b.HasIndex("DepId");

                    b.HasIndex("EmpManagerId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("MikesBank.Models.Location", b =>
                {
                    b.Property<int>("LocId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocAddress1");

                    b.Property<string>("LocAddress2");

                    b.Property<string>("LocCity");

                    b.Property<string>("LocCountry");

                    b.Property<string>("LocName");

                    b.Property<string>("LocZip");

                    b.Property<string>("UpdateBy");

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("LocId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("MikesBank.Models.Logging", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogMessage");

                    b.Property<string>("LogSeverity");

                    b.Property<string>("LogSource");

                    b.Property<string>("LogStackTrace");

                    b.Property<string>("UpdateBy");

                    b.Property<DateTime?>("UpdateTime");

                    b.HasKey("LogId");

                    b.ToTable("Logging");
                });

            modelBuilder.Entity("MikesBank.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(6);

                    b.Property<string>("Level")
                        .HasMaxLength(5);

                    b.Property<string>("Name");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("MikesBank.Models.Department", b =>
                {
                    b.HasOne("MikesBank.Models.Location", "Loc")
                        .WithMany("Department")
                        .HasForeignKey("LocId");
                });

            modelBuilder.Entity("MikesBank.Models.Employee", b =>
                {
                    b.HasOne("MikesBank.Models.Department", "Dep")
                        .WithMany("Employee")
                        .HasForeignKey("DepId");

                    b.HasOne("MikesBank.Models.Employee", "EmpManager")
                        .WithMany("InverseEmpManager")
                        .HasForeignKey("EmpManagerId");
                });

            modelBuilder.Entity("MikesBank.Models.Profession", b =>
                {
                    b.HasOne("MikesBank.Models.Profession", "SupCategory")
                        .WithMany("SubCategory")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
